### ISSUE TITLE
Remove PIC from comments

### ISSUE THREAD

**Issue by nerdralph** [WestfW/OptiLoader#15]
I guess a much older version of this code was written for a PIC.

https://github.com/WestfW/OptiLoader/blob/master/optiLoader.ino#L44

**Comment by WestfW** [comment]
Heh.  I think that was a "think-o" on my part.  The sketch is essentially the ArduinoISP sketch, with the source of data changed, and I added the "power from a pin" code and comments.  I just didn't type it quite right :-)
